### ISSUE TITLE
Remove bad PNG and SVG files generated by SBFC

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/temp-biomodels#102]
Some images just display error messages. This is similar to other problems with the [SBFC](https://sourceforge.net/projects/sbfc/), especially #98.

## Examples
* PNG: https://github.com/sys-bio/temp-biomodels/blob/main/manual-fixes/BIOMD0000000585/BIOMD0000000585.png
* SVG: https://github.com/sys-bio/temp-biomodels/blob/main/manual-fixes/BIOMD0000000585/BIOMD0000000585.svg

## Todo
- [x] Report PNG issue to the [SBFC issue tracker](https://sourceforge.net/p/sbfc/bugs/)
- [x] Report SVG issue to the [SBFC issue tracker](https://sourceforge.net/p/sbfc/bugs/)
- [x] Detect bad SVG files by looking for SVG that contains the string "no graph can be automatically generated." I think we can safely assume that if the SVG is bad, so is the PNG (since the PNG is likely created from the SVG).
- [x] Remove bad SVG and PNG images
- [ ] Incorporate this into biomodels-qc for SVG and PNG

This should be done by 
- [x] Write a Python script, using any of the `fix_*.py` scripts in this root of this repository as a template
- [x] Import this new script into [fix-entries.py](https://github.com/sys-bio/temp-biomodels/blob/main/fix-entries.py).
