### ISSUE TITLE
Add curators notes and images

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/temp-biomodels#103]
I think it would be helpful to have this here so it can also be corrected

## Todo
- Use requests to scrape the BioModels page for each record of the database.
- Parse the description, curation notes, and other metadata from these pages. Encode this information into RDF. Export this information to an RDF-XML file. 
- Parse the curation images from these pages. Save them to (likely PNG) files.
- Commit the RDF-XML and image files to this repository.

This should be done by 
- [x] Write a Python script, using any of the `fix_*.py` scripts in this root of this repository as a template
  - [x] Read curation notes from BioModels website
    - [x] Save curation notes to `original` subdirectory
  - [x] Download curation images from BioModels website
- [x] Import this new script into [fix-entries.py](https://github.com/sys-bio/temp-biomodels/blob/main/fix-entries.py).
