### ISSUE TITLE
Correct character encoding issues in SED-ML files

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/temp-biomodels#104]
Similar to #100, there are also weirdly encoded characters in the SED-ML files which would ideally be fixed.

Example: https://github.com/sys-bio/temp-biomodels/blob/main/final/BIOMD0000000585/PC_100.sedml#L479 (`Î³` rather than `γ`)

## Todo
For each SED-ML file,
1. Open the SED-ML file
2. Identify such odd characters in the file. #100 has notes about useful Python packages for correcting this.
3. If the intended character can be discerned, replace it with the intended utf8 character. If not, replace it the character with a `?`
4. Save the modified SED-ML

This should be done by 
- [ ] Write a Python script, using any of the `fix_*.py` scripts in this root of this repository as a template
- [ ] Import this new script into [fix-entries.py](https://github.com/sys-bio/temp-biomodels/blob/main/fix-entries.py).
- [ ] Incorporate validation for this into [validate_sedml_file](https://github.com/sys-bio/temp-biomodels/blob/bce3c167dd728deb1b24651e4fe4c25abd56aa57/biomodels_qc/biomodels_qc/validation.py#L383)
